@echo off
setlocal
cd /d "%~dp0"
echo Checking container state...
docker compose ps -a
echo Checking Tor configuration without starting Tor...
docker compose run --rm --no-deps tor tor --verify-config -f /etc/tor/torrc
echo Checking SearXNG settings without submitting a search...
docker compose run --rm --no-deps --entrypoint /usr/local/searxng/.venv/bin/python searxng -c "import searx; print('SearXNG settings loaded successfully')"
echo Checking browser connection...
curl.exe --noproxy "*" -i --max-time 5 http://127.0.0.1:8787/api/health
pause
